
[package]
name = "void_survivor"
version = "0.0.2-dev"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_rapier3d = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
rand = "0.8"

[[bin]]
name = "void_survivor"
path = "src/main.rs"
