
[package]
name = "void_survivor"
version = "0.0.1-init"
edition = "2021"

[dependencies]
bevy = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
rand = "0.8"

[[bin]]
name = "void_survivor"
path = "src/main.rs"
