
[package]
name = "void_survivor"
version = "0.0.1-init"
edition = "2021"

[dependencies]
fyrox = {workspace = true}
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"

[features]
default = ["fyrox/default"]
dylib-engine = ["fyrox/dylib"]
