
[package]
name = "executor"
version = "0.0.1-init"
edition = "2021"

[dependencies]
fyrox = { workspace = true }
void_survivor = { path = "../game", optional = true }

[features]
default = ["void_survivor"]
dylib = ["fyrox/dylib"]
